---
title: "DataFest 2020"
author: "GoDuck"
date: "2020-5-14"
output: html_document
---

Anyi Chen anyichen@ucla.edu | Miao Xu xumiao@ucla.edu | Xinyue Gui shirleygxy@ucla.edu | Yurui Zhang yuruizhang9734@ucla.edu


```{r}
library(readxl)
rmc_perc <- read_excel('Percent Change From 1947.xlsx', range = "B8:KI37")
rmc_perc <- rmc_perc[-25, ]
type <- rmc_perc[, 1]

firstcol <- which(colnames(rmc_perc)=="2018Q1")
lastcol <- which(colnames(rmc_perc)=="2020Q1")

covid_perc <- cbind(type, rmc_perc[c(firstcol:lastcol)])
covid_perc
```

```{r}
sorted <- covid_perc
sorted$diff <- sorted$'2020Q1' - sorted$'2019Q4'
sorted <- sorted[order(sorted$diff), ]
sorted
```

### Sorted table

```{r}
library(formattable)
num <- as.vector(unlist(t(sorted[1:9,c(-1,-11)])))
percent_change <- matrix(num, nrow=9, byrow=TRUE)
mat <- cbind(sorted[,1], percent_change)

null_table <- as.data.frame(mat)

colnames(null_table) <- c("Industry","2018Q1","2018Q2","2018Q3","2018Q4","2019Q1","2019Q2","2019Q3","2019Q4","2020Q1")
# null_table

formattable(null_table,align = c("l",rep("r", NCOL(null_table) - 1)),
            list('Comment_Type' = formatter("span", style = ~ style(color = "grey", font.weight = "bold")),
            area(col = 2:10) ~ color_tile('white', 'lightblue2')))
            
```

### Colors By Columns

```{r}
library(formattable)
num <- as.vector(unlist(t(covid_perc[,-1])))
percent_change <- matrix(num, nrow=28, byrow=TRUE)
mat <- cbind(type, percent_change)

null_table <- as.data.frame(mat)

colnames(null_table) <- c("Industry","2018Q1","2018Q2","2018Q3","2018Q4","2019Q1","2019Q2","2019Q3","2019Q4","2020Q1")
# null_table

formattable(null_table,align = c("l",rep("r", NCOL(null_table) - 1)),
            list('Comment_Type' = formatter("span", style = ~ style(color = "grey", font.weight = "bold")),
            area(col = 2) ~ color_tile('white', 'peachpuff1'),
            area(col = 3) ~ color_tile('white', 'peachpuff2'),
            area(col = 4) ~ color_tile('white', 'lightpink1'),
            area(col = 5) ~ color_tile('white', 'lightpink1'),
            area(col = 6) ~ color_tile('white', 'rosybrown1'),
            area(col = 7) ~ color_tile('white', 'rosybrown1'),
            area(col = 8) ~ color_tile('white', 'rosybrown2'),
            area(col = 9) ~ color_tile('white', 'lightblue3'),
            area(col = 10) ~ color_tile('white', 'lightblue3')))
            
```

### Colors By Rows

```{r}
library(formattable)
num <- as.vector(unlist(t(covid_perc[,-1])))
percent_change <- matrix(num, nrow=28, byrow=TRUE)
mat <- cbind(type, percent_change)

null_table <- as.data.frame(mat)

colnames(null_table) <- c("Industry","2018Q1","2018Q2","2018Q3","2018Q4","2019Q1","2019Q2","2019Q3","2019Q4","2020Q1")
# null_table

formattable(null_table,align = c("l",rep("r", NCOL(null_table) - 1)),
            list('Comment_Type' = formatter("span", style = ~ style(color = "grey", font.weight = "bold")),
            area(row = 1) ~ color_tile('white', 'peachpuff1'),
            area(row = 2) ~ color_tile('white', 'peachpuff2'),
            area(row = 3) ~ color_tile('white', 'lightpink1'),
            area(row = 4) ~ color_tile('white', 'lightpink1'),
            area(row = 5) ~ color_tile('white', 'lightpink1'),
            area(row = 6) ~ color_tile('white', 'lightpink1'),
            area(row = 7) ~ color_tile('white', 'lightpink1'),
            area(row = 8) ~ color_tile('white', 'lightblue2'),
            area(row = 9) ~ color_tile('white', 'lightblue2'),
            area(row = 10) ~ color_tile('white', 'lightblue2'),
            area(row = 11) ~ color_tile('white', 'lightblue2'),
            area(row = 12) ~ color_tile('white', 'lightblue2'),
            area(row = 13) ~ color_tile('white', 'rosybrown1'),
            area(row = 14) ~ color_tile('white', 'rosybrown1'),
            area(row = 15) ~ color_tile('white', 'rosybrown1'),
            area(row = 16) ~ color_tile('white', 'rosybrown1'),
            area(row = 17) ~ color_tile('white', 'rosybrown1'),
            area(row = 18) ~ color_tile('white', 'rosybrown1'),
            area(row = 19) ~ color_tile('white', 'rosybrown1'),
            area(row = 20) ~ color_tile('white', 'rosybrown1'),
            area(row = 21) ~ color_tile('white', 'rosybrown1'),
            area(row = 22) ~ color_tile('white', 'lightblue3'),
            area(row = 23) ~ color_tile('white', 'lightblue3'),
            area(row = 24) ~ color_tile('white', 'lightblue3'),
            area(row = 25) ~ color_tile('white', 'lightblue3'),
            area(row = 26) ~ color_tile('white', 'lightblue3'),
            area(row = 27) ~ color_tile('white', 'lightblue3'),
            area(row = 28) ~ color_tile('white', 'lightblue3')))
```